// AUTO-GENERATED by scripts/generate_analysis.py — 2026-05-15 08:34 UTC
import type { BlogPost } from '@/types';

export const blogPosts: BlogPost[] = [
  {
    id: "blog-20260515-01",
    tag: "EPL Analysis",
    titleEn: "Aston Villa Host Liverpool in a High-Scoring Premier League Matchup\n\nEXCERPT_EN: Aston Villa will face Liverpool in a Premier League match that is expected to be full of goals. Our analysts have tipped over 2.5 goals in this matchup.\n\nBODY_EN: Aston Villa has been in decent form recently, securing three wins in their last five matches, but they still struggle to maintain consistency. They have conceded an average of 1.4 goals per match in their last five Premier League games.\n\nAston Villa has a mixed history against Liverpool. They have won twice, drawn twice, and lost twice in their last six meetings. However, their last meeting at Villa Park was a 1-1 draw.\n\nOur analysts believe that Liverpool's attacking prowess will be too much for Aston Villa's defense, especially given the home team's recent inconsistency. With Liverpool's ability to score multiple goals in a single match, we expect this matchup to go over 2.5 goals.\n\nTITLE_AM: በማስተዋወቃት አትካጂን በየኢትዮጵያ አስተዋወቃት ላይ\n\nEXCERPT_AM: በአትካጂን ተይጃ በፖርማይስላንድ ልማት ወደ ጋሎ እንደሚገባ የተላከፈ የማስተዋወቃት ወሳኝ ነው. ያላተምረው የማስተዋወቃት ስራተኝ፤ አስተዋወቀ የሁለት በጥቂ ልማታዊ ጊዜዎች\n\nBODY_AM: አስተዋወቃት አትካጂን በብአዙለቀ ማስተዋወቃት፤ በስምንት ጊዜ በስድስት ጊዜ ይሁ",
    titleAm: "በማስተዋወቃት አትካጂን በየኢትዮጵያ አስተዋወቃት ላይ\n\nEXCERPT_AM: በአትካጂን ተይጃ በፖርማይስላንድ ልማት ወደ ጋሎ እንደሚገባ የተላከፈ የማስተዋወቃት ወሳኝ ነው. ያላተምረው የማስተዋወቃት ስራተኝ፤ አስተዋወቀ የሁለት በጥቂ ልማታዊ ጊዜዎች\n\nBODY_AM: አስተዋወቃት አትካጂን በብአዙለቀ ማስተዋወቃት፤ በስምንት ጊዜ በስድስት ጊዜ ይሁ",
    excerptEn: "Aston Villa will face Liverpool in a Premier League match that is expected to be full of goals. Our analysts have tipped over 2.5 goals in this matchup.\n\nBODY_EN: Aston Villa has been in decent form recently, securing three wins in their last five matches, but they still struggle to maintain consistency. They have conceded an average of 1.4 goals per match in their last five Premier League games.\n\nAston Villa has a mixed history against Liverpool. They have won twice, drawn twice, and lost twice in their last six meetings. However, their last meeting at Villa Park was a 1-1 draw.\n\nOur analysts believe that Liverpool's attacking prowess will be too much for Aston Villa's defense, especially given the home team's recent inconsistency. With Liverpool's ability to score multiple goals in a single match, we expect this matchup to go over 2.5 goals.\n\nTITLE_AM: በማስተዋወቃት አትካጂን በየኢትዮጵያ አስተዋወቃት ላይ\n\nEXCERPT_AM: በአትካጂን ተይጃ በፖርማይስላንድ ልማት ወደ ጋሎ እንደሚገባ የተላከፈ የማስተዋወቃት ወሳኝ ነው. ያላተምረው የማስተዋወቃት ስራተኝ፤ አስተዋወቀ የሁለት በጥቂ ልማታዊ ጊዜዎች\n\nBODY_AM: አስተዋወቃት አትካጂን በብአዙለቀ ማስተዋወቃት፤ በስምንት ጊዜ በስድስት ጊዜ ይሁ",
    excerptAm: "በአትካጂን ተይጃ በፖርማይስላንድ ልማት ወደ ጋሎ እንደሚገባ የተላከፈ የማስተዋወቃት ወሳኝ ነው. ያላተምረው የማስተዋወቃት ስራተኝ፤ አስተዋወቀ የሁለት በጥቂ ልማታዊ ጊዜዎች\n\nBODY_AM: አስተዋወቃት አትካጂን በብአዙለቀ ማስተዋወቃት፤ በስምንት ጊዜ በስድስት ጊዜ ይሁ",
    bodyEn: "Aston Villa has been in decent form recently, securing three wins in their last five matches, but they still struggle to maintain consistency. They have conceded an average of 1.4 goals per match in their last five Premier League games.\n\nAston Villa has a mixed history against Liverpool. They have won twice, drawn twice, and lost twice in their last six meetings. However, their last meeting at Villa Park was a 1-1 draw.\n\nOur analysts believe that Liverpool's attacking prowess will be too much for Aston Villa's defense, especially given the home team's recent inconsistency. With Liverpool's ability to score multiple goals in a single match, we expect this matchup to go over 2.5 goals.",
    bodyAm: "አስተዋወቃት አትካጂን በብአዙለቀ ማስተዋወቃት፤ በስምንት ጊዜ በስድስት ጊዜ ይሁ",
    date: "May 15, 2026",
    readTime: "4 min read",
    thumbEmoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    thumbClass: "from-purple-900 to-purple-600",
    homeTeam: "Aston Villa",
    awayTeam: "Liverpool",
    homeLogoUrl: "",
    awayLogoUrl: "",
  },
];
