// AUTO-GENERATED by scripts/generate_analysis.py — 2026-05-20 08:49 UTC
import type { BlogPost } from '@/types';

export const blogPosts: BlogPost[] = [
  {
    id: "blog-20260520-01",
    tag: "Europa League",
    titleEn: "SC Freiburg vs Aston Villa: Europa League Showdown\n\nEXCERPT_EN: SC Freiburg is currently on a five-game unbeaten streak but faces a tough test against Aston Villa. Aston Villa has been in decent form as well, winning three of their last five matches.\n\nBODY_EN: SC Freiburg has been in impressive form, with a five-game unbeaten streak that sees them sitting comfortably in the top four of the Bundesliga. However, their European campaign has been inconsistent, and they will need to draw on their domestic experience to take on the English Premier League side.\n\nTheir past encounters have been relatively rare, but the teams have met once before in a Europa League match in 2005. SC Freiburg won that match 4-0, but that was over two decades ago.\n\nOur prediction leans towards Aston Villa winning outright, with the English side having the momentum and the quality to outplay the German team. With a 50% confidence level, our tip for this match is Aston Villa to win, priced at 1.69 odds.",
    titleAm: "",
    excerptEn: "SC Freiburg is currently on a five-game unbeaten streak but faces a tough test against Aston Villa. Aston Villa has been in decent form as well, winning three of their last five matches.\n\nBODY_EN: SC Freiburg has been in impressive form, with a five-game unbeaten streak that sees them sitting comfortably in the top four of the Bundesliga. However, their European campaign has been inconsistent, and they will need to draw on their domestic experience to take on the English Premier League side.\n\nTheir past encounters have been relatively rare, but the teams have met once before in a Europa League match in 2005. SC Freiburg won that match 4-0, but that was over two decades ago.\n\nOur prediction leans towards Aston Villa winning outright, with the English side having the momentum and the quality to outplay the German team. With a 50% confidence level, our tip for this match is Aston Villa to win, priced at 1.69 odds.",
    excerptAm: "",
    bodyEn: "SC Freiburg has been in impressive form, with a five-game unbeaten streak that sees them sitting comfortably in the top four of the Bundesliga. However, their European campaign has been inconsistent, and they will need to draw on their domestic experience to take on the English Premier League side.\n\nTheir past encounters have been relatively rare, but the teams have met once before in a Europa League match in 2005. SC Freiburg won that match 4-0, but that was over two decades ago.\n\nOur prediction leans towards Aston Villa winning outright, with the English side having the momentum and the quality to outplay the German team. With a 50% confidence level, our tip for this match is Aston Villa to win, priced at 1.69 odds.",
    bodyAm: "",
    date: "May 20, 2026",
    readTime: "4 min read",
    thumbEmoji: "🟠",
    thumbClass: "from-purple-900 to-purple-600",
    homeTeam: "SC Freiburg",
    awayTeam: "Aston Villa",
    homeLogoUrl: "",
    awayLogoUrl: "",
  },
];
