// AUTO-GENERATED by scripts/fetch_data.py — 2026-05-08 07:12 UTC
import type { Match } from '@/types';

export const matches: Match[] = [
  {
    id: "match-748491",
    league: "laliga",
    home: "Levante",
    away: "Osasuna",
    kickoff: "19:00",
    status: "upcoming",
  },
  {
    id: "match-747008",
    league: "bundesliga",
    home: "Borussia Dortmund",
    away: "Eintracht Frankfurt",
    kickoff: "18:30",
    status: "upcoming",
  },
  {
    id: "match-737143",
    league: "seriea",
    home: "Torino",
    away: "Sassuolo",
    kickoff: "18:45",
    status: "upcoming",
  },
  {
    id: "match-746702",
    league: "ligue1",
    home: "Lens",
    away: "Nantes",
    kickoff: "18:45",
    status: "upcoming",
  },
];
