// AUTO-GENERATED by scripts/fetch_data.py — 2026-05-22 08:45 UTC
import type { Match } from '@/types';

export const matches: Match[] = [
  {
    id: "match-737161",
    league: "seriea",
    home: "Fiorentina",
    away: "Atalanta",
    kickoff: "18:45",
    status: "upcoming",
  },
];
