// AUTO-GENERATED by scripts/fetch_data.py — 2026-05-05 00:39 UTC
import type { Match } from '@/types';

export const matches: Match[] = [
  {
    id: "match-401862896",
    league: "ucl",
    home: "Arsenal",
    away: "Atl\u00e9tico Madrid",
    kickoff: "19:00",
    status: "upcoming",
  },
];
