// AUTO-GENERATED by scripts/fetch_data.py — 2026-07-25 07:46 UTC
import type { LeagueTableRow } from '@/types';

export const eplStandings: LeagueTableRow[] = [
  { position: 1, team: "AFC Bournemouth", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 2, team: "Arsenal", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 3, team: "Aston Villa", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 4, team: "Brentford", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 5, team: "Brighton & Hove Albion", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 6, team: "Chelsea", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 7, team: "Coventry City", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 8, team: "Crystal Palace", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 9, team: "Everton", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 10, team: "Fulham", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 11, team: "Hull City", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 12, team: "Ipswich Town", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 13, team: "Leeds United", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 14, team: "Liverpool", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 15, team: "Manchester City", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 16, team: "Manchester United", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 17, team: "Newcastle United", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 18, team: "Nottingham Forest", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 19, team: "Sunderland", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { position: 20, team: "Tottenham Hotspur", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
];

export const ethStandings: LeagueTableRow[] = [
  { position: 1,  team: 'Saint George',    played: 26, won: 17, drawn: 5, lost: 4,  gd: 28,  points: 56 },
  { position: 2,  team: 'Fasil Kenema',    played: 26, won: 15, drawn: 6, lost: 5,  gd: 22,  points: 51 },
  { position: 3,  team: 'Wolkite City',    played: 26, won: 14, drawn: 5, lost: 7,  gd: 15,  points: 47 },
  { position: 4,  team: 'Hawassa Ketema',  played: 26, won: 12, drawn: 7, lost: 7,  gd: 10,  points: 43 },
  { position: 5,  team: 'Adama City',      played: 26, won: 11, drawn: 6, lost: 9,  gd: 4,   points: 39 },
  { position: 6,  team: 'Jimma Aba Jifar', played: 26, won: 10, drawn: 7, lost: 9,  gd: 2,   points: 37 },
  { position: 7,  team: 'Dedebit',         played: 26, won: 9,  drawn: 8, lost: 9,  gd: -1,  points: 35 },
  { position: 8,  team: 'Dire Dawa',       played: 26, won: 8,  drawn: 7, lost: 11, gd: -5,  points: 31 },
  { position: 9,  team: 'Bahir Dar Kenema',played: 26, won: 7,  drawn: 6, lost: 13, gd: -10, points: 27 },
  { position: 10, team: 'Arba Minch',      played: 26, won: 6,  drawn: 5, lost: 15, gd: -15, points: 23 },
  { position: 11, team: 'Sidama Bunna',    played: 26, won: 5,  drawn: 6, lost: 15, gd: -18, points: 21 },
  { position: 12, team: 'Wolaita Dicha',   played: 26, won: 4,  drawn: 4, lost: 18, gd: -32, points: 16 },
];
