// AUTO-GENERATED by scripts/fetch_data.py — 2026-05-22 08:45 UTC
import type { LeagueTableRow } from '@/types';

export const eplStandings: LeagueTableRow[] = [
  { position: 1, team: "Arsenal", played: 37, won: 25, drawn: 7, lost: 5, gd: 43, points: 82 },
  { position: 2, team: "Manchester City", played: 37, won: 23, drawn: 9, lost: 5, gd: 43, points: 78 },
  { position: 3, team: "Manchester United", played: 37, won: 19, drawn: 11, lost: 7, gd: 16, points: 68 },
  { position: 4, team: "Aston Villa", played: 37, won: 18, drawn: 8, lost: 11, gd: 6, points: 62 },
  { position: 5, team: "Liverpool", played: 37, won: 17, drawn: 8, lost: 12, gd: 10, points: 59 },
  { position: 6, team: "AFC Bournemouth", played: 37, won: 13, drawn: 17, lost: 7, gd: 4, points: 56 },
  { position: 7, team: "Brighton & Hove Albion", played: 37, won: 14, drawn: 11, lost: 12, gd: 9, points: 53 },
  { position: 8, team: "Chelsea", played: 37, won: 14, drawn: 10, lost: 13, gd: 7, points: 52 },
  { position: 9, team: "Brentford", played: 37, won: 14, drawn: 10, lost: 13, gd: 3, points: 52 },
  { position: 10, team: "Sunderland", played: 37, won: 13, drawn: 12, lost: 12, gd: -7, points: 51 },
  { position: 11, team: "Newcastle United", played: 37, won: 14, drawn: 7, lost: 16, gd: 0, points: 49 },
  { position: 12, team: "Everton", played: 37, won: 13, drawn: 10, lost: 14, gd: -2, points: 49 },
  { position: 13, team: "Fulham", played: 37, won: 14, drawn: 7, lost: 16, gd: -6, points: 49 },
  { position: 14, team: "Leeds United", played: 37, won: 11, drawn: 14, lost: 12, gd: -4, points: 47 },
  { position: 15, team: "Crystal Palace", played: 37, won: 11, drawn: 12, lost: 14, gd: -9, points: 45 },
  { position: 16, team: "Nottingham Forest", played: 37, won: 11, drawn: 10, lost: 16, gd: -3, points: 43 },
  { position: 17, team: "Tottenham Hotspur", played: 37, won: 9, drawn: 11, lost: 17, gd: -10, points: 38 },
  { position: 18, team: "West Ham United", played: 37, won: 9, drawn: 9, lost: 19, gd: -22, points: 36 },
  { position: 19, team: "Burnley", played: 37, won: 4, drawn: 9, lost: 24, gd: -37, points: 21 },
  { position: 20, team: "Wolverhampton Wanderers", played: 37, won: 3, drawn: 10, lost: 24, gd: -41, points: 19 },
];

export const ethStandings: LeagueTableRow[] = [
  { position: 1,  team: 'Saint George',    played: 26, won: 17, drawn: 5, lost: 4,  gd: 28,  points: 56 },
  { position: 2,  team: 'Fasil Kenema',    played: 26, won: 15, drawn: 6, lost: 5,  gd: 22,  points: 51 },
  { position: 3,  team: 'Wolkite City',    played: 26, won: 14, drawn: 5, lost: 7,  gd: 15,  points: 47 },
  { position: 4,  team: 'Hawassa Ketema',  played: 26, won: 12, drawn: 7, lost: 7,  gd: 10,  points: 43 },
  { position: 5,  team: 'Adama City',      played: 26, won: 11, drawn: 6, lost: 9,  gd: 4,   points: 39 },
  { position: 6,  team: 'Jimma Aba Jifar', played: 26, won: 10, drawn: 7, lost: 9,  gd: 2,   points: 37 },
  { position: 7,  team: 'Dedebit',         played: 26, won: 9,  drawn: 8, lost: 9,  gd: -1,  points: 35 },
  { position: 8,  team: 'Dire Dawa',       played: 26, won: 8,  drawn: 7, lost: 11, gd: -5,  points: 31 },
  { position: 9,  team: 'Bahir Dar Kenema',played: 26, won: 7,  drawn: 6, lost: 13, gd: -10, points: 27 },
  { position: 10, team: 'Arba Minch',      played: 26, won: 6,  drawn: 5, lost: 15, gd: -15, points: 23 },
  { position: 11, team: 'Sidama Bunna',    played: 26, won: 5,  drawn: 6, lost: 15, gd: -18, points: 21 },
  { position: 12, team: 'Wolaita Dicha',   played: 26, won: 4,  drawn: 4, lost: 18, gd: -32, points: 16 },
];
